print('Basic String Output')
print('-'*20)
print()
print('Hello, World')
print('*'*30)
print('Simple Math Inside Print')
print('-'*20)
print()
print(5+3)
print('*'*30)
print('Multiple Arguments in Print')
print('-'*20)
print()
print('Python','Is','Fun')
print('*'*30)
print('with Escape Characters')
print('-'*20)
print()
print('She said, \'Hello!\'')
print('*'*30)
print('Newline Character')
print('-'*20)
print()
print("First line\nSecond line")
print('*'*30)
print('Tab Character')
print('-'*20)
print()
print("Item 1\tItem 2\tItem 3")
print('*'*30)
print('Multiple Data Types Together')
print('-'*20)
print()
print("The result is", 42)
print('*'*30)
print('a Single Number')
print('-'*20)
print()
print(12345)
print('*'*30)
print('a Decimal Number')
print('-'*20)
print()
print(3.14159)
print('*'*30)
print('Special Characters')
print('-'*20)
print()
print("Dollar sign: $")
print('*'*30)
print('Using the sep Parameter')
print('-'*20)
print()
print("apple", "banana", "cherry", sep=", ")
print('*'*30)
print('Using the end Parameter')
print('-'*20)
print()
print("Hello,", end=" ")
print("World!")
print('*'*30)
print('a Repeated String')
print('-'*20)
print()
print("Python! " * 3)
print('*'*30)
print('a Unicode Character')
print('-'*20)
print()
print("\u2764") # Prints a heart symbol
print('*'*30)
print('Empty Line')
print('-'*20)
print()
print()
print('*'*30)
print('Concatenating Strings Inside Print')
print('-'*20)
print()
print("Hello " + "World!")
print('*'*30)
print('Boolean Values')
print('-'*20)
print()
print(True)
print(False)
print('*'*30)
print('Exponential Notation')
print('-'*20)
print()
print(1.2e3) # Prints 1200.0
print('*'*30)
print('Multiline Text Using Triple Quotes')
print('-'*20)
print()
print("""This is a multiline
print statement.""")
print('*'*30)
print('Using Escaped Backslash')
print('-'*20)
print()
print("This is a backslash: \\")
print('*'*30)
print()
